#!/bin/sh

playbook=${1:-./play.yml}

if [ ! -f "$playbook" ]; then
  printf 'No playbook was specified.\n'
  printf 'Usage: %s [play.yml]\n' "$0"
  exit 1
fi

generate_username() {
  length="$1"
  date +%s%N \
  | sha256sum \
  | base64 \
  | tr -d 'ilA-Z0' \
  | head -c "$length"
}

generate_password() {
  length="$1"
  date +%s%N \
  | sha256sum \
  | base64 \
  | tr -d 'ilLOZ0' \
  | head -c "$length"
}

generate_secrets() {
  mysql_database="$(generate_username 6)"
  mysql_username="$(generate_username 6)"
  mysql_password="$(generate_password 12)"
  mysql_root_password="$(generate_password 12)"

  wordpress_username="$(generate_username 6)"
  wordpress_password="$(generate_password 6)"

  redis_password="$(generate_password 12)"
}

enter_secrets_into_playbook() {
  sed -i -e "s/^\(\s*mysql_database\:\s\).*/\1$mysql_database/" "$playbook"
  sed -i -e "s/^\(\s*mysql_username\:\s\).*/\1$mysql_username/" "$playbook"
  sed -i -e "s/^\(\s*mysql_password\:\s\).*/\1$mysql_password/" "$playbook"
  sed -i -e "s/^\(\s*mysql_root_password\:\s\).*/\1$mysql_root_password/" "$playbook"

  sed -i -e "s/^\(\s*wordpress_username\:\s\).*/\1$wordpress_username/" "$playbook"
  sed -i -e "s/^\(\s*wordpress_password\:\s\).*/\1$wordpress_password/" "$playbook"

  sed -i -e "s/^\(\s*redis_password\:\s\).*/\1$redis_password/" "$playbook"
}

output_secrets() {
  printf 'Secrets generated!\n----------------------------------\n'
  printf 'mysql_database      : %s\n' "$mysql_database"
  printf 'mysql_username      : %s\n' "$mysql_username"
  printf 'mysql_password      : %s\n' "$mysql_password"
  printf 'mysql_root_password : %s\n\n' "$mysql_root_password"

  printf 'redis_password      : %s\n\n' "$redis_password"

  printf 'wordpress_username  : %s\n' "$wordpress_username"
  printf 'wordpress_password  : %s\n' "$wordpress_password"
}

generate_secrets
enter_secrets_into_playbook
output_secrets
