version: 2
jobs:
  build:
    docker:
      - image: blacklabelops/virtualbox
    working_directory: ~/alpine
    steps:
      - checkout
      - run: uname -a
      - run: /sbin/rcvboxdrv setup
      - run: packer build template.json
